version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      day: saturday
      interval: weekly
      time: '02:45'
      timezone: Etc/UTC
  - package-ecosystem: npm
    directory: /
    schedule:
      day: saturday
      interval: weekly
      time: '02:45'
      timezone: Etc/UTC
    versioning-strategy: increase
