name: Analyze the code quality
#on:
#  push:
#    branches:
#      - primary
#  pull_request:
#    branches:
#      - primary
jobs:
  analyze:
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Build CodeQL
        uses: github/codeql-action/autobuild@v2
        # If `autobuild` fails, remove it and uncomment the following 3 lines:
        # run: |
        #   make bootstrap
        #   make release
      - name: Perform the analysis
        uses: github/codeql-action/analyze@v2
    strategy:
      matrix:
        language:
          # `javascript` corresponds to both JavaScript and TypeScript.
          # See <https://github.com/github/codeql-action/issues/365/>.
          - javascript
      fail-fast: false
