name: Publish the package
#on:
#  push:
#    tags:
#      - '**'
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up a Node.js environment
        uses: actions/setup-node@v3
        with:
          # `actions/setup-node` provides cacheable images of LTS releases.
          node-version: '14.17.0'

          cache: npm
          cache-dependency-path: npm-shrinkwrap.json

          # Will be used when creating the `.npmrc` file.
          registry-url: https://registry.npmjs.org/
      - name: Build the package
        run: |
          npm ci --ignore-scripts
          npm run build
      - name: Publish the package
        # Instead of `npm publish --access=...`,
        # use `publishConfig.access` in `package.json`.
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
