name: Test
on:
  push:
    branches:
      - primary
  pull_request:
    branches:
      - primary
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up a Node.js ${{ matrix.node }} environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

          # See <https://github.com/actions/setup-node/pull/299/>.
          # cache: npm
      - name: Test
        run: |
          npm ci --ignore-scripts
          npm run lint
          npm run build
          npm test
    strategy:
      matrix:
        node:
          # `engines.node` in `package.json` is the production environment.
          # `actions/setup-node` provides cacheable images of LTS releases.
          - '14.15.0'
        os:
          - ubuntu-20.04
          - windows-2019
